// src/app/layout.tsx

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { LanguageProvider } from "@/contexts/LanguageContext";
import { RegionProvider } from "@/contexts/RegionContext";
import { AuthProvider } from "@/contexts/AuthContext";
import { getSession } from "@/lib/session";
import { StructuredData } from "@/components/StructuredData";
import type { AppSession, RegionData, Language } from "@/types"; // <-- ensure this path is correct

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Cast getSession() result to our AppSession | null so TS knows the optional fields exist
  const session = (await getSession()) as AppSession | null;

  const language: Language = session?.language ?? "en";

  // region shape should match RegionData in src/types.ts
  const region: RegionData = session?.region ?? {
    country: "IN",
    code: "IN",
    city: undefined,
    state: undefined,
  };

  const user = session?.user ?? null;

  return (
    <html lang={language}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <StructuredData />
        <LanguageProvider initialLanguage={language}>
          <RegionProvider initialRegion={region}>
            <AuthProvider initialUser={user}>{children}</AuthProvider>
          </RegionProvider>
        </LanguageProvider>
      </body>
    </html>
  );
}
